/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtDots: typeof import('./../components/ArtDots.vue')['default']
    ArtPlum: typeof import('./../components/ArtPlum.vue')['default']
    Flip: typeof import('./../components/css/Flip.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./../components/ToggleTheme.vue')['default']
  }
}

// For TSX support
declare global {
  const ArtDots: typeof import('./../components/ArtDots.vue')['default']
  const ArtPlum: typeof import('./../components/ArtPlum.vue')['default']
  const Flip: typeof import('./../components/css/Flip.vue')['default']
  const Footer: typeof import('./../components/Footer.vue')['default']
  const Logo: typeof import('./../components/Logo.vue')['default']
  const NavBar: typeof import('./../components/NavBar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ToggleTheme: typeof import('./../components/ToggleTheme.vue')['default']
}