/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/demos/': RouteRecordInfo<
      '/demos/',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/ai': RouteRecordInfo<
      '/demos/ai',
      '/demos/ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/bff': RouteRecordInfo<
      '/demos/bff',
      '/demos/bff',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/browser': RouteRecordInfo<
      '/demos/browser',
      '/demos/browser',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/carousel': RouteRecordInfo<
      '/demos/carousel',
      '/demos/carousel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/cors': RouteRecordInfo<
      '/demos/cors',
      '/demos/cors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/css': RouteRecordInfo<
      '/demos/css',
      '/demos/css',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/docker': RouteRecordInfo<
      '/demos/docker',
      '/demos/docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/engineering': RouteRecordInfo<
      '/demos/engineering',
      '/demos/engineering',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/es6+': RouteRecordInfo<
      '/demos/es6+',
      '/demos/es6+',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/event-loop': RouteRecordInfo<
      '/demos/event-loop',
      '/demos/event-loop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/js': RouteRecordInfo<
      '/demos/js',
      '/demos/js',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/network': RouteRecordInfo<
      '/demos/network',
      '/demos/network',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/nodejs': RouteRecordInfo<
      '/demos/nodejs',
      '/demos/nodejs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/operations': RouteRecordInfo<
      '/demos/operations',
      '/demos/operations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/react': RouteRecordInfo<
      '/demos/react',
      '/demos/react',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/storage': RouteRecordInfo<
      '/demos/storage',
      '/demos/storage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/vue3': RouteRecordInfo<
      '/demos/vue3',
      '/demos/vue3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resume/': RouteRecordInfo<
      '/resume/',
      '/resume',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/demos/index.md': {
      routes:
        | '/demos/'
      views:
        | never
    }
    'pages/demos/ai.md': {
      routes:
        | '/demos/ai'
      views:
        | never
    }
    'pages/demos/bff.md': {
      routes:
        | '/demos/bff'
      views:
        | never
    }
    'pages/demos/browser.md': {
      routes:
        | '/demos/browser'
      views:
        | never
    }
    'pages/demos/carousel.md': {
      routes:
        | '/demos/carousel'
      views:
        | never
    }
    'pages/demos/cors.md': {
      routes:
        | '/demos/cors'
      views:
        | never
    }
    'pages/demos/css.md': {
      routes:
        | '/demos/css'
      views:
        | never
    }
    'pages/demos/docker.md': {
      routes:
        | '/demos/docker'
      views:
        | never
    }
    'pages/demos/engineering.md': {
      routes:
        | '/demos/engineering'
      views:
        | never
    }
    'pages/demos/es6+.md': {
      routes:
        | '/demos/es6+'
      views:
        | never
    }
    'pages/demos/event-loop.md': {
      routes:
        | '/demos/event-loop'
      views:
        | never
    }
    'pages/demos/js.md': {
      routes:
        | '/demos/js'
      views:
        | never
    }
    'pages/demos/network.md': {
      routes:
        | '/demos/network'
      views:
        | never
    }
    'pages/demos/nodejs.md': {
      routes:
        | '/demos/nodejs'
      views:
        | never
    }
    'pages/demos/operations.md': {
      routes:
        | '/demos/operations'
      views:
        | never
    }
    'pages/demos/react.md': {
      routes:
        | '/demos/react'
      views:
        | never
    }
    'pages/demos/storage.md': {
      routes:
        | '/demos/storage'
      views:
        | never
    }
    'pages/demos/vue3.md': {
      routes:
        | '/demos/vue3'
      views:
        | never
    }
    'pages/resume/index.md': {
      routes:
        | '/resume/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
